// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"archie-core-shopify-layer/graph/scalars"
)

type ConfigureCredentialsInput struct {
	ProjectID   string `json:"projectId"`
	Environment string `json:"environment"`
	APIKey      string `json:"apiKey"`
	APISecret   string `json:"apiSecret"`
}

type ConfigureCredentialsPayload struct {
	Credentials *ShopifyCredentials `json:"credentials"`
}

type ConfigureShopifyInput struct {
	APIKey        string  `json:"apiKey"`
	APISecret     string  `json:"apiSecret"`
	WebhookSecret *string `json:"webhookSecret,omitempty"`
}

type ConfigureShopifyPayload struct {
	ID          string       `json:"id"`
	ProjectID   string       `json:"projectId"`
	Environment string       `json:"environment"`
	APIKey      string       `json:"apiKey"`
	WebhookURL  string       `json:"webhookUrl"`
	CreatedAt   scalars.Time `json:"createdAt"`
	UpdatedAt   scalars.Time `json:"updatedAt"`
}

type CreateIntegrationInput struct {
	ProjectID   string `json:"projectId"`
	Environment string `json:"environment"`
	ShopDomain  string `json:"shopDomain"`
}

type CreateIntegrationPayload struct {
	Integration *Integration `json:"integration"`
}

type Customer struct {
	ID          string       `json:"id"`
	Email       *string      `json:"email,omitempty"`
	FirstName   *string      `json:"firstName,omitempty"`
	LastName    *string      `json:"lastName,omitempty"`
	OrdersCount *int         `json:"ordersCount,omitempty"`
	TotalSpent  *string      `json:"totalSpent,omitempty"`
	CreatedAt   scalars.Time `json:"createdAt"`
	UpdatedAt   scalars.Time `json:"updatedAt"`
}

type ExchangeTokenInput struct {
	Shop  string  `json:"shop"`
	Code  string  `json:"code"`
	State *string `json:"state,omitempty"` // Optional: used to retrieve redirect_uri from session
}

type ExchangeTokenPayload struct {
	Shop        *Shop  `json:"shop"`
	AccessToken string `json:"accessToken"`
}

type InstallAppInput struct {
	Shop        string   `json:"shop"`
	Scopes      []string `json:"scopes"`
	ReturnURL   *string  `json:"returnUrl,omitempty"`
	RedirectURI *string  `json:"redirectUri,omitempty"`
	APIKey      *string  `json:"apiKey,omitempty"`
	APISecret   *string  `json:"apiSecret,omitempty"`
}

type InstallAppPayload struct {
	AuthURL string `json:"authUrl"`
}

type Integration struct {
	ID          string       `json:"id"`
	Key         string       `json:"key"`
	ProjectID   string       `json:"projectId"`
	Environment string       `json:"environment"`
	ShopDomain  string       `json:"shopDomain"`
	CreatedAt   scalars.Time `json:"createdAt"`
	UpdatedAt   scalars.Time `json:"updatedAt"`
}

type InventoryLevel struct {
	InventoryItemID string       `json:"inventoryItemId"`
	LocationID      string       `json:"locationId"`
	Available       *int         `json:"available,omitempty"`
	UpdatedAt       scalars.Time `json:"updatedAt"`
}

type Mutation struct {
}

type Order struct {
	ID                string       `json:"id"`
	OrderNumber       int          `json:"orderNumber"`
	Email             *string      `json:"email,omitempty"`
	TotalPrice        string       `json:"totalPrice"`
	FinancialStatus   *string      `json:"financialStatus,omitempty"`
	FulfillmentStatus *string      `json:"fulfillmentStatus,omitempty"`
	CreatedAt         scalars.Time `json:"createdAt"`
	UpdatedAt         scalars.Time `json:"updatedAt"`
}

type Product struct {
	ID          string       `json:"id"`
	Title       string       `json:"title"`
	Handle      *string      `json:"handle,omitempty"`
	Vendor      *string      `json:"vendor,omitempty"`
	ProductType *string      `json:"productType,omitempty"`
	CreatedAt   scalars.Time `json:"createdAt"`
	UpdatedAt   scalars.Time `json:"updatedAt"`
}

type Query struct {
}

type Shop struct {
	ID        string       `json:"id"`
	Domain    string       `json:"domain"`
	Scopes    []string     `json:"scopes"`
	CreatedAt scalars.Time `json:"createdAt"`
	UpdatedAt scalars.Time `json:"updatedAt"`
}

type ShopifyConfig struct {
	ID          string       `json:"id"`
	ProjectID   string       `json:"projectId"`
	Environment string       `json:"environment"`
	APIKey      string       `json:"apiKey"`
	WebhookURL  string       `json:"webhookUrl"`
	CreatedAt   scalars.Time `json:"createdAt"`
	UpdatedAt   scalars.Time `json:"updatedAt"`
}

type ShopifyCredentials struct {
	ID          string       `json:"id"`
	ProjectID   string       `json:"projectId"`
	Environment string       `json:"environment"`
	APIKey      string       `json:"apiKey"`
	CreatedAt   scalars.Time `json:"createdAt"`
	UpdatedAt   scalars.Time `json:"updatedAt"`
}

type Subscription struct {
}

type WebhookEvent struct {
	ID        string       `json:"id"`
	Topic     string       `json:"topic"`
	Shop      string       `json:"shop"`
	Verified  bool         `json:"verified"`
	CreatedAt scalars.Time `json:"createdAt"`
}

type WebhookEventFilter struct {
	Topics []string `json:"topics,omitempty"`
	Shop   *string  `json:"shop,omitempty"`
}

type WebhookEventPayload struct {
	ID        string       `json:"id"`
	Topic     string       `json:"topic"`
	Shop      string       `json:"shop"`
	Verified  bool         `json:"verified"`
	Payload   string       `json:"payload"`
	CreatedAt scalars.Time `json:"createdAt"`
}
