apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archie-core-shopify-layer.fullname" . }}-secrets
  namespace: {{ include "archie-core-shopify-layer.namespace" . }}
  labels:
    {{- include "archie-core-shopify-layer.labels" . | nindent 4 }}
type: Opaque
stringData:
  # MongoDB Configuration (sensitive)
  {{- if .Values.mongodb.uri }}
  MONGODB_URI: {{ .Values.mongodb.uri | quote }}
  {{- end }}
  
  # Redis Configuration (sensitive)
  {{- if .Values.redis.url }}
  REDIS_URL: {{ .Values.redis.url | quote }}
  {{- end }}
  
  # Encryption Configuration (sensitive)
  {{- if .Values.encryption.key }}
  ENCRYPTION_KEY: {{ .Values.encryption.key | quote }}
  {{- end }}
  
  # Shopify Configuration (sensitive)
  {{- if .Values.shopify.apiKey }}
  SHOPIFY_API_KEY: {{ .Values.shopify.apiKey | quote }}
  {{- end }}
  {{- if .Values.shopify.apiSecret }}
  SHOPIFY_API_SECRET: {{ .Values.shopify.apiSecret | quote }}
  {{- end }}

